apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../conf/dev
  - deployment.yaml
  - analytics-tailnet.yaml
  - maps-rbac.yaml
  - osm-import-config.yaml
patches:
  - path: analytics-tailnet-patch.yaml
