---
apiVersion: v1
kind: Service
metadata:
    name: std-dive-logger-autocomplete-dev
    namespace: std-dive-logger
spec:
    type: ClusterIP
    ports:
        -   port: 5173
    selector:
        app: std-dive-logger-autocomplete-dev
