### Get Dives for user
GET {{baseurl}}/v1/dives

### Create user
POST {{baseurl}}/api/auth/signup
Content-Type: application/json

{
  "email": "test1@test.ch",
  "password": "AcBd321#",
  "name": "Test1User"
}

### Login user
POST {{baseurl}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.ch",
  "password": "AcBd321#"
}

### Create Dive Site
POST {{baseurl}}/v1/dives/sites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY2giLCJpYXQiOjE3NjQ5MjQzODcsImV4cCI6MTc2NDkyNzk4N30.HqHk7rZKDzrbgWR553ZnThGE9t7DGrVgn-6HSFGN_K22LykWr2v38ou2qH89V0T4

{
  "lat": 46.123,
  "lon": 9.123,
  "name": "Test Site"
}

### Get Dives
GET {{baseurl}}/v1/dives
Authorization: Bearer

### Generate Preview Dive Image
POST {{baseurl}}/v1/dives/14/preview
Authorization: Bearer

### Get List<DiveSite> for user
GET {{baseurl}}/v1/dives/sites
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY2giLCJpYXQiOjE3NjQ5MjQzODcsImV4cCI6MTc2NDkyNzk4N30.HqHk7rZKDzrbgWR553ZnThGE9t7DGrVgn-6HSFGN_K22LykWr2v38ou2qH89V0T4

### Local Login
POST {{baseurl}}/api/auth/login
Content-Type: application/json

{
  "email": "test@test.ch",
  "password": "abc123"
}
