### Get Dives for user
GET {{baseurl}}/v1/dives

### Create user
POST {{baseurl}}/api/auth/signup
Content-Type: application/json

{
  "email": "test1@test.ch",
  "password": "AcBd321#"
}

### Login user
POST {{baseurl}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.ch",
  "password": "AcBd321#"
}
