package ch.sthomas.stddivelogger.model.importer;

public class SqliteDBFile {
    private SqliteDBFile() {}

    public record DiveDetails(
            String diveId,
            Long dataVersion,
            String fileName,
            String lastModified,
            String mainTimestampReliable,
            String diveDate,
            String depth,
            String serialNumber,
            Double averageDepth,
            Double averageTemp,
            Double minTemp,
            Double maxTemp,
            Double endGF99,
            String diveLengthTime,
            String location,
            String site,
            String buddy,
            String dateAndTime,
            String diveNumber,
            String environment,
            String environmentNotes,
            String visibility,
            String weather,
            String conditions,
            String platform,
            String airTemperature,
            String gnssEntryLocation,
            String gnssExitLocation,
            String gnssCustomWaypoints,
            String tankProfileData,
            String tank1PressureStart,
            String tank1PressureEnd,
            String tank2PressureStart,
            String tank2PressureEnd,
            String tank3PressureStart,
            String tank3PressureEnd,
            String tank4PressureStart,
            String tank4PressureEnd,
            String averageSAC,
            String tankSize,
            String gasNotes,
            String weight,
            String gearNotes,
            String dress,
            String apparatus,
            String thermalComfort,
            String workload,
            String problems,
            String malfunctions,
            String symptoms,
            String exposureToAltitude,
            String notes,
            String other1,
            String other2,
            String other3,
            String issueNotes,
            String aveloNotes) {}

    public record DiveLogRecord(
            Long id,
            String diveLogId,
            Long currentTime,
            Double currentDepth,
            Long firstStopDepth,
            Long ttsMins,
            Double averagePPO2,
            Double fractionO2,
            Double fractionHe,
            Long firstStopTime,
            Long currentNdl,
            Long systemByte,
            Long currentCircuitSetting,
            Long currentCcrMode,
            Long waterTemp,
            Long errorAcks,
            Long errorFlags,
            Long gasSwitchNeeded,
            Long externalPPO2,
            Long setPointType,
            Long circuitSwitchType,
            Long sensor1Millivolts,
            Long sensor2Millivolts,
            Long sensor3Millivolts,
            Double batteryVoltage,
            Long backlightCurrent,
            Long currentPPO2SetPoint,
            Long lightLevelReading,
            Long cnsPercent,
            Long decoCeiling,
            Long gf99,
            Double safeAscentDepth,
            Long atPlusFive,
            Long aiSensor0BatteryLevel,
            Long aiSensor0PressurePSI,
            Long aiSensor1BatteryLevel,
            Long aiSensor1PressurePSI,
            Long aiSensor2BatteryLevel,
            Long aiSensor2PressurePSI,
            Long aiSensor3BatteryLevel,
            Long aiSensor3PressurePSI,
            Long gasTime,
            Double respiratoryMinuteVolume,
            Double ascentRate,
            Long batteryPercentRemaining,
            Long hpDilPressure,
            Long hpO2Pressure,
            byte[] rawBytes) {}

    public record DeletedLog(String diveId, String deletedAsOf) {}

    public record LogData(
            String logId,
            Long tableVersion,
            Long createdUnixTime,
            Long modifiedUnixTime,
            String fileName,
            String format,
            Long formatVersion,
            String calculatedValuesFromSamples,
            byte[] dataBytes1,
            byte[] dataBytes2,
            byte[] dataBytes3,
            byte[] dataBytes4) {}

    public record SyncV3MetadataDiveDetail(
            String id,
            String lastModifiedDevice,
            String lastModifiedServerTime,
            String createdDevice,
            String createdTime,
            String fieldTimeStampJson,
            Long version) {}

    public record SyncV3MetadataDelete(
            String id,
            String lastModifiedDevice,
            String lastModifiedServerTime,
            String createdDevice,
            String createdTime,
            Long version) {}

    public record SwcTableVersion(Long id, Long dbVersion, Long updated) {}

    public record SyncV3MetadataDiveLog(
            String id,
            String lastModifiedDevice,
            String lastModifiedServerTime,
            String createdDevice,
            String createdTime) {}

    public record StoredDiveComputer(Long serialNumber, Long version, String jsonData) {}

    public record IdToDiveComputer(
            Long serialNumber, Long version, String diveComputerConnectionId) {}

    public record CustomDiveComputer(
            Long serialNumber, Long version, String updateTime, String jsonData) {}

    public record DiveSite(
            String guid,
            String geoHash,
            String name,
            String location,
            String region,
            String country,
            String countryCode,
            Double latitude,
            Double longitude,
            String timestamps,
            Long modelVersion,
            Long createdAt,
            Long modifiedAt) {}

    // Note: The 'dive_logs' table has ~200 columns.
    // Java Records can handle this, but it is verbose.
    //    public record DiveLog(
    //            Long id,
    //            String diveId,
    //            String primaryKey,
    //            Long diveAutoInc,
    //            Long number,
    //            Long gfMin,
    //            Long gfMax,
    //            Long surfaceMins,
    //            Long imperialUnits,
    //            Double startBatteryVoltage,
    //            Long startCNS,
    //            String startDate,
    //            Long startO2SensorStatus,
    //            Long startLowSetPoint,
    //            Long startHighSetPoint,
    //            Long computerFirmware,
    //            Long maxDepth,
    //            Double maxDepthFloat,
    //            Long maxTime,
    //            Long errorHistory,
    //            Double endBatteryVoltage,
    //            Long endCNS,
    //            String endDate,
    //            Long endO2SensorStatus,
    //            Long endLowSetPoint,
    //            Long endHighSetPoint,
    //            Long computerSerial,
    //            Long computerSoftwareVersion,
    //            Long computerModel,
    //            Long logVersion,
    //            Long dbVersion,
    //            Long startTimestamp,
    //            Long endTimeStamp,
    //            Long decoModel,
    //            Long vpmbConservatism,
    //            Long startSurfacePressure,
    //            Long endSurfacePressure,
    //            Long sensorDisplay,
    //            Long product,
    //            Long features,
    //            Long startGFS,
    //            Long startSensor1Calibrated,
    //            Long startSensor2Calibrated,
    //            Long startSensor3Calibrated,
    //            Long startSensor1CalibrationValue,
    //            Long startSensor2CalibrationValue,
    //            Long startSensor3CalibrationValue,
    //            Double startSensor1ADCOffset,
    //            Double startSensor2ADCOffset,
    //            Double startSensor3ADCOffset,
    //            Long startO2DecoMode,
    //            Long startO2TempGender,
    //            Long startO2TempWeight,
    //            Long startBatteryGaugeAvailable,
    //            Long startBatteryPercentage,
    //            Long startBatteryType,
    //            Long startBatterySetting,
    //            Long startBatteryWarningLevel,
    //            Long startBatteryCriticalLevel,
    //            Long startHSITrimLocation,
    //            Long startLogVersion,
    //            Long endSensor1Calibrated,
    //            Long endSensor2Calibrated,
    //            Long endSensor3Calibrated,
    //            Long endSensor1CalibrationValue,
    //            Long endSensor2CalibrationValue,
    //            Long endSensor3CalibrationValue,
    //            Double endSensor1ADCOffset,
    //            Double endSensor2ADCOffset,
    //            Double endSensor3ADCOffset,
    //            Long endO2DecoMode,
    //            Long endO2TempGender,
    //            Long endO2TempWeight,
    //            Long endBatteryGaugeAvailable,
    //            Long endBatteryPercentage,
    //            Long endBatteryType,
    //            Long endBatterySetting,
    //            Long endBatteryWarningLevel,
    //            Long endBatteryCriticalLevel,
    //            Long endHSITrimLocation,
    //            Long endLogVersion,
    //            Double maxDescentRateMbarPerMinute,
    //            Double maxAscentRateMbarPerMinute,
    //            Double avgDescentRateMbarPerMinute,
    //            Double avgAscentRateMbarPerMinute,
    //            Long startComputerSerialNumber,
    //            Long timeZoneOffsetInMinutes,
    //            Long daylightSavings,
    //            Long headerSurfaceTime,
    //            Long headerO2Sensor1Status,
    //            Long headerO2Sensor2Status,
    //            Long headerO2Sensor3Status,
    //            Long headerOcGas0O2Percent,
    //            Long headerOcGas1O2Percent,
    //            Long headerOcGas2O2Percent,
    //            Long headerOcGas3O2Percent,
    //            Long headerOcGas4O2Percent,
    //            Long headerOcGas0HePercent,
    //            Long headerOcGas1HePercent,
    //            Long headerOcGas2HePercent,
    //            Long headerOcGas3HePercent,
    //            Long headerOcGas4HePercent,
    //            Long headerCcGas0O2Percent,
    //            Long headerCcGas1O2Percent,
    //            Long headerCcGas2O2Percent,
    //            Long headerCcGas3O2Percent,
    //            Long headerCcGas4O2Percent,
    //            Long headerCcGas0HePercent,
    //            Long headerCcGas1HePercent,
    //            Long headerCcGas2HePercent,
    //            Long headerCcGas3HePercent,
    //            Long headerCcGas4HePercent,
    //            Long headerSwitchUpSetting,
    //            Long headerSwitchUpDepth,
    //            Long headerSwitchDownSetting,
    //            Long headerSwitchDownDepth,
    //            Long headerO2SensorMode,
    //            String headerErrorFlags0,
    //            String headerErrorFlags1,
    //            String headerErrorFlags2,
    //            String headerErrorFlags3,
    //            String headerErrorAcks0,
    //            String headerErrorAcks1,
    //            String headerErrorAcks2,
    //            String headerErrorAcks3,
    //            Long headerCurrentEventLogNumber,
    //            Long headerSolenoidDepthCompensation,
    //            Double headerOcMinimumPPO2,
    //            Double headerOcMaximumPPO2,
    //            Double headerOcDecoPPO2,
    //            Double headerCcMinimumPPO2,
    //            Double headerCcMaximumPPO2,
    //            Long headerDecoViolatedDisplayed,
    //            Long headerLastStopDepth,
    //            Long headerEndDiveDelay,
    //            Long headerClockFormat,
    //            Long headerTitleColor,
    //            Long headerShowOCOnlyPPO2,
    //            Long headerSalinity,
    //            Long headerCo2TempEnabled,
    //            Long headerCo2TempWarmupFlags,
    //            Long headerCo2TempReadyFlags,
    //            Long headerCo2TempScrubberState,
    //            Long headerCo2TempCurrentRct,
    //            Long headerCo2TempCurrentRst,
    //            Long headerCo2TempMinimumRct,
    //            Long headerCo2TempMinimumRctDiveMinutes,
    //            Long headerCo2TempMinimumRst,
    //            Long headerCo2TempMinimumRstDiveMinutes,
    //            Long headerMode,
    //            Long headerGasState,
    //            Long headerAIMode,
    //            Long headerGTRMode,
    //            Long headerAIUnit,
    //            String headerAIT1SerialNumber,
    //            Long headerAIT1TankSize,
    //            Long headerAIT1MaxPressure,
    //            Long headerAIT1ReservePressure,
    //            Long headerAIT1On,
    //            String headerAIT1Name,
    //            String headerAIT2SerialNumber,
    //            Long headerAIT2TankSize,
    //            Long headerAIT2MaxPressure,
    //            Long headerAIT2ReservePressure,
    //            Long headerAIT2On,
    //            String headerAIT2Name,
    //            String headerAIT3SerialNumber,
    //            Long headerAIT3MaxPressure,
    //            Long headerAIT3ReservePressure,
    //            Long headerAIT3On,
    //            String headerAIT3Name,
    //            String headerAIT4SerialNumber,
    //            Long headerAIT4MaxPressure,
    //            Long headerAIT4ReservePressure,
    //            Long headerAIT4On,
    //            String headerAIT4Name,
    //            Long headerSideMountSwitchPressure,
    //            Long headerExtendedDiveSampleIndicator,
    //            Long headerOem,
    //            Long headerLang,
    //            Long headerOCRecSubMode,
    //            Long headerTotalStackTimeInSeconds,
    //            Long headerRemainingStackTimeInSeconds,
    //            Long headerTotalOnTimeInSeconds,
    //            Long headerDepthAlertEnabled,
    //            Double headerDepthAlertValue,
    //            Long headerTimeAlertEnabled,
    //            Long headerTimeAlertValueInMinutes,
    //            Long headerLowNdlAlertEnabled,
    //            Long headerLowNdlAlertValueInMinutes,
    //            Long footerSurfaceTime,
    //            Long footerTempUnitSystem,
    //            Double internalBatteryVoltage,
    //            Double internalBatteryVoltageD100,
    //            Double footerInternalBatteryVoltageD100,
    //            Long footerO2Sensor1Status,
    //            Long footerO2Sensor2Status,
    //            Long footerO2Sensor3Status,
    //            Long footerOcGas0O2Percent,
    //            Long footerOcGas1O2Percent,
    //            Long footerOcGas2O2Percent,
    //            Long footerOcGas3O2Percent,
    //            Long footerOcGas4O2Percent,
    //            Long footerOcGas0HePercent,
    //            Long footerOcGas1HePercent,
    //            Long footerOcGas2HePercent,
    //            Long footerOcGas3HePercent,
    //            Long footerOcGas4HePercent,
    //            Long footerCcGas0O2Percent,
    //            Long footerCcGas1O2Percent,
    //            Long footerCcGas2O2Percent,
    //            Long footerCcGas3O2Percent,
    //            Long footerCcGas4O2Percent,
    //            Long footerCcGas0HePercent,
    //            Long footerCcGas1HePercent,
    //            Long footerCcGas2HePercent,
    //            Long footerCcGas3HePercent,
    //            Long footerCcGas4HePercent,
    //            Long footerSwitchUpSetting,
    //            Long footerSwitchUpDepth,
    //            Long footerSwitchDownSetting,
    //            Long footerSwitchDownDepth,
    //            Long footerO2SensorMode,
    //            Long footerSurfacePressure,
    //            String footerErrorFlags0,
    //            String footerErrorFlags1,
    //            String footerErrorFlags2,
    //            String footerErrorFlags3,
    //            String footerErrorAcks0,
    //            String footerErrorAcks1,
    //            String footerErrorAcks2,
    //            String footerErrorAcks3,
    //            Long footerCurrentEventLogNumber,
    //            Long footerSolenoidDepthCompensation,
    //            Long footerOcMinimumPPO2,
    //            Long footerOcMaximumPPO2,
    //            Long footerOcDecoPPO2,
    //            Long footerCcMinimumPPO2,
    //            Long footerCcMaximumPPO2,
    //            Long footerDecoViolatedDisplayed,
    //            Long footerLastStopDepth,
    //            Long footerEndDiveDelay,
    //            Long footerClockFormat,
    //            Long footerTitleColor,
    //            Long footerShowOCOnlyPPO2,
    //            Long footerSalinity,
    //            Long footerGfs,
    //            Long footerCo2TempEnabled,
    //            Long footerCo2TempWarmupFlags,
    //            Long footerCo2TempReadyFlags,
    //            Long footerCo2TempScrubberState,
    //            Long footerCo2TempCurrentRct,
    //            Long footerCo2TempCurrentRst,
    //            Long footerCo2TempMinimumRct,
    //            Long footerCo2TempMinimumRctDiveMinutes,
    //            Long footerCo2TempMinimumRst,
    //            Long footerCo2TempMinimumRstDiveMinutes,
    //            Long footerMode,
    //            Long footerGasState,
    //            Long footerAIMode,
    //            Long footerGTRMode,
    //            Long footerAIUnit,
    //            String footerAIT1SerialNumber,
    //            Long footerAIT1TankSize,
    //            Long footerAIT1MaxPressure,
    //            Long footerAIT1ReservePressure,
    //            Long footerAIT1On,
    //            String footerAIT1Name,
    //            String footerAIT2SerialNumber,
    //            Long footerAIT2TankSize,
    //            Long footerAIT2MaxPressure,
    //            Long footerAIT2ReservePressure,
    //            Long footerAIT2On,
    //            String footerAIT2Name,
    //            String footerAIT3SerialNumber,
    //            Long footerAIT3TankSize,
    //            Long footerAIT3MaxPressure,
    //            Long footerAIT3ReservePressure,
    //            Long footerAIT3On,
    //            String footerAIT3Name,
    //            String footerAIT4SerialNumber,
    //            Long footerAIT4TankSize,
    //            Long footerAIT4MaxPressure,
    //            Long footerAIT4ReservePressure,
    //            Long footerAIT4On,
    //            String footerAIT4Name,
    //            Long footerSideMountSwitchPressure,
    //            Long footerExtendedDiveSampleIndicator,
    //            Long footerAverageDiveDepth,
    //            Long footerDiveTimeInSeconds,
    //            Long logChecksum,
    //            Long footerOem,
    //            Long footerLang,
    //            Double footerAverageSacPSIPerMin,
    //            Long footerOCRecSubMode,
    //            Long footerTotalStackTimeInSeconds,
    //            Long footerRemainingStackTimeInSeconds,
    //            Long footerTotalOnTimeInSeconds,
    //            Long footerDepthAlertEnabled,
    //            Double footerDepthAlertValue,
    //            Long footerTimeAlertEnabled,
    //            Long footerTimeAlertValueInMinutes,
    //            Long footerLowNdlAlertEnabled,
    //            Long footerLowNdlAlertValueInMinutes,
    //            Long sampleRateMs) {}
}
