<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>std-dive-logger-backend</artifactId>
        <groupId>ch.sthomas.stddivelogger</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>std-dive-logger-service</artifactId>
    <name>Std Dive Logger Service</name>

    <dependencies>
        <!-- Module dependencies -->
        <dependency>
            <groupId>ch.sthomas.stddivelogger</groupId>
            <artifactId>std-dive-logger-data</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.passay</groupId>
            <artifactId>passay</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-svggen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-dom</artifactId>
        </dependency>


        <!-- shared test -->
        <dependency>
            <groupId>ch.sthomas.stddivelogger</groupId>
            <artifactId>std-dive-logger-data</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>Jar Tests Package</id>
                        <phase>package</phase>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
