server.port=8080

spring.profiles.active=email,no-security
spring.application.name=std-dive-logger-ws-local

spring.jpa.open-in-view=false
spring.web.resources.add-mappings=false
server.servlet.encoding.force=true

logging.config=classpath:logback-spring.xml
logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]

# Swagger UI properties (See: https://springdoc.org/#swagger-ui-properties)
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs/swagger-ui
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=2
springdoc.swagger-ui.syntaxHighlight.theme=arta

# Database
spring.datasource.hikari.max-lifetime=600000
spring.flyway.locations=classpath:/db/migration/{vendor}

# Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.server.port=${server.port}

# Feign
spring.cloud.openfeign.client.config.default.logger-level=basic
spring.cloud.openfeign.client.config.default.connectTimeout=10000

spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=80MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${java.io.tmpdir}

ch.sthomas.stddivelogger.ws.services.feign.autocomplete.url=http://localhost:5173

ch.sthomas.stddivelogger.ws.jwt-secret=${STD_DIVE_LOGGER_WS_JWT_SECRET}
ch.sthomas.stddivelogger.ws.jwt-refresh-secret=${STD_DIVE_LOGGER_WS_JWT_REFRESH_SECRET}

ch.sthomas.stddivelogger.ws.security.same_site_cookie=false
ch.sthomas.stddivelogger.ws.cors.allowed_origins=https://std-dive-logger-web-dev.sthomas.ch,https://localhost:3000
ch.sthomas.stddivelogger.frontend.base-url=https://localhost:3000

ch.sthomas.stddivelogger.storage.r2.bucket=${STD_DIVE_LOGGER_STORAGE_R2_BUCKET}
ch.sthomas.stddivelogger.storage.r2.account-id=${STD_DIVE_LOGGER_STORAGE_R2_ACCOUNT_ID}
ch.sthomas.stddivelogger.storage.r2.access-key=${STD_DIVE_LOGGER_STORAGE_R2_ACCESS_KEY}
ch.sthomas.stddivelogger.storage.r2.secret-key=${STD_DIVE_LOGGER_STORAGE_R2_SECRET_KEY}
ch.sthomas.stddivelogger.storage.r2.base-url=${STD_DIVE_LOGGER_STORAGE_R2_BASE_URL}

ch.sthomas.stddivelogger.users.check-verified=false
ch.sthomas.stddivelogger.email.address=${EMAIL}
ch.sthomas.stddivelogger.email.password=${PASSWORD}
ch.sthomas.stddivelogger.email.host=${HOST}
ch.sthomas.stddivelogger.email.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
