server.port=8081

spring.profiles.active=no-security
spring.application.name=std-dive-logger-autocomplete-local

spring.jpa.open-in-view=false
spring.web.resources.add-mappings=false
server.servlet.encoding.force=true

logging.config=classpath:logback-spring.xml
logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]

# Swagger UI properties (See: https://springdoc.org/#swagger-ui-properties)
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs/swagger-ui
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=2
springdoc.swagger-ui.syntaxHighlight.theme=arta

# Database
spring.datasource.hikari.max-lifetime=600000
spring.flyway.locations=classpath:/db/migration/{vendor}

# Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.server.port=${server.port}

ch.sthomas.stddivelogger.autocomplete.cors.allowed_origins=https://localhost:5173,${EXTRA_CORS_URLS}

spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${java.io.tmpdir}
