apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: std-dive-logger-autocomplete-config
    files:
      - std-dive-logger-autocomplete-dev.properties
      - std-dive-logger-autocomplete-dev-logback.xml
