ALTER TABLE t_dive_measurements
    ADD COLUMN IF NOT EXISTS n2 DOUBLE PRECISION;
ALTER TABLE t_dive_measurements
    ADD COLUMN IF NOT EXISTS o2_tox DOUBLE PRECISION;
ALTER TABLE t_dive_measurements
    ADD COLUMN IF NOT EXISTS cns DOUBLE PRECISION;
