apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: std-dive-logger-import-ws-dev-ingress-rule
    namespace: ingress-basic
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - std-dive-logger-import-ws-dev.sthomas.ch
            secretName: tls-secret-std-dive-logger-import-ws-dev
    rules:
        -   host: std-dive-logger-import-ws-dev.sthomas.ch
            http:
                paths:
                    -   backend:
                            service:
                                name: std-dive-logger-import-ws-dev
                                port:
                                    number: 8080
                        path: /
                        pathType: Prefix


---
apiVersion: v1
kind: Service
metadata:
    name: std-dive-logger-import-ws-dev
    namespace: ingress-basic
spec:
    type: ExternalName
    externalName: std-dive-logger-import-ws-dev.std-dive-logger.svc.cluster.local
    ports:
        -   port: 8080
            targetPort: 8080
            protocol: TCP
            name: http8080
