---
apiVersion: v1
kind: Service
metadata:
    name: std-dive-logger-import-ws-dev
    namespace: std-dive-logger
spec:
    type: ClusterIP
    ports:
        -   port: 8080
    selector:
        app: std-dive-logger-import-ws-dev
