spring.application.name=std-dive-logger-ws-dev

spring.jpa.open-in-view=false
spring.web.resources.add-mappings=false
spring.mvc.log-resolved-exception=false
server.servlet.encoding.force=true

logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]

spring.docker.compose.enabled=false

# database settings are injected via env vars/k8s secrets
# SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD
spring.datasource.hikari.poolName=db-pool
spring.datasource.hikari.maximumPoolSize=8
spring.datasource.hikari.max-lifetime=600000
spring.flyway.locations=classpath:/db/migration/postgresql
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Swagger UI properties (See: https://springdoc.org/#swagger-ui-properties)
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs/swagger-ui
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=2
springdoc.swagger-ui.syntaxHighlight.theme=arta

# Prometheus
management.endpoints.web.exposure.include=*

management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=read_only

management.prometheus.metrics.export.enabled=true
management.observations.annotations.enabled=true

management.server.port=8086

# Feign
spring.cloud.openfeign.client.config.default.logger-level=basic
spring.cloud.openfeign.client.config.default.connectTimeout=10000

# Multipart Upload
spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=80MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${java.io.tmpdir}

# Inject ch.sthomas.stddivelogger.ws.services.feign.autocomplete.url as ENV:
# CH_STHOMAS_STDDIVELOGGER_WS_SERVICES_FEIGN_AUTOCOMPLETE_URL
# ch.sthomas.stddivelogger.ws.services.feign.autocomplete.url=${AUTOCOMPLETE_URL}

ch.sthomas.stddivelogger.ws.jwt-secret=${STD_DIVE_LOGGER_WS_JWT_SECRET}
ch.sthomas.stddivelogger.ws.jwt-refresh-secret=${STD_DIVE_LOGGER_WS_JWT_REFRESH_SECRET}

# Okay on Dev, but CSRF risk
ch.sthomas.stddivelogger.ws.security.same_site_cookie=false
ch.sthomas.stddivelogger.ws.cors.allowed_origins=https://localhost:3000,${EXTRA_CORS_URLS}
ch.sthomas.stddivelogger.frontend.base-url=${FRONTEND_BASE_URL}

ch.sthomas.stddivelogger.storage.r2.bucket=${STD_DIVE_LOGGER_STORAGE_R2_BUCKET}
ch.sthomas.stddivelogger.storage.r2.account-id=${STD_DIVE_LOGGER_STORAGE_R2_ACCOUNT_ID}
ch.sthomas.stddivelogger.storage.r2.access-key=${STD_DIVE_LOGGER_STORAGE_R2_ACCESS_KEY}
ch.sthomas.stddivelogger.storage.r2.secret-key=${STD_DIVE_LOGGER_STORAGE_R2_SECRET_KEY}
ch.sthomas.stddivelogger.storage.r2.base-url=${STD_DIVE_LOGGER_STORAGE_R2_BASE_URL}
STD_DIVE_LOGGER_STORAGE_R2_TOKEN_UNUSED=
