spring.application.name=std-dive-logger-ws-dev

spring.jpa.open-in-view=false
spring.web.resources.add-mappings=false
spring.mvc.log-resolved-exception=false
server.servlet.encoding.force=true

logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]

spring.docker.compose.enabled=false

# database settings are injected via env vars/k8s secrets
# SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD
spring.datasource.hikari.maximumPoolSize=3
spring.datasource.hikari.max-lifetime=600000
spring.flyway.locations=classpath:/db/migration/postgresql

# Swagger UI properties (See: https://springdoc.org/#swagger-ui-properties)
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs/swagger-ui
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=2
springdoc.swagger-ui.syntaxHighlight.theme=arta

# Prometheus
management.endpoints.web.exposure.include=*

management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=read_only

management.prometheus.metrics.export.enabled=true
management.observations.annotations.enabled=true

management.server.port=8086

# Feign
spring.cloud.openfeign.client.config.default.logger-level=basic
spring.cloud.openfeign.client.config.default.connectTimeout=10000

# Multipart Upload
spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=80MB

# TODO: Fill in correct URL
ch.sthomas.stddivelogger.ws.services.feign.importer.url=https://api.

ch.sthomas.stddivelogger.ws.jwt-secret=${STD_DIVE_LOGGER_WS_JWT_SECRET}
